@server = http://localhost:8000
@json = application/json
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoNHZydXQ0IiwidXNlcklkIjoiMzQ2MDBlNjAtOTRmNC00ZDM4LWIwNWQtNGQ5M2JiM2ZkMDE3IiwidHlwZSI6IkFDQ0VTUyIsImlhdCI6MTc3MDAxMTE4OSwiZXhwIjoxNzcwMDEyMDg5fQ.G2KnjebcFV46w3ip03Oe4E2Zwv0QjoIwc3F6dEqm_3E
@refreshToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJ1aWQiOjYsInR5cGUiOiJSRUZSRVNIIiwiaWF0IjoxNzY4MjMyNzI1LCJleHAiOjE3Njk0NDIzMjV9.rTokMpr0y0WbdbJ2K4TKJl89Gemmy6ECYh8b8vbUn58

GET {{server}}/products/all
Authorization: Bearer {{accessToken}}
########################################
GET {{server}}/products/health
Authorization: Bearer {{accessToken}}
########################################
POST {{server}}/products/create
Authorization: Bearer {{accessToken}}
Content-Type: {{json}}

{
    "name": "The Wall",
    "artistName": "Pink Floyd",
    "year": 1979,
    "condition": "MINT",
    "price": 65000,
    "stock": 5,
    "isLimited": true,
    "saleStartAt": "2026-02-10T10:00:00"
}
########################################
GET {{server}}/users/me
Authorization: Bearer {{accessToken}}
### 1️⃣ 회원가입 (permitAll)
########################################
POST {{server}}/auth/register
Content-Type: {{json}}

{
  "username": "h4vrut4",
  "password": "H$VRUT$",
  "name": "aa",
  "email": "abc@naver.com"
}

########################################
### 2️⃣ 로그인 (permitAll)
### → accessToken 반환
########################################
POST {{server}}/auth/login
Content-Type: {{json}}

{
  "username": "h4vrut4",
  "password": "H$VRUT$"
}

########################################
### 2️⃣ 로그아웃
########################################
POST {{server}}/auth/logout
Authorization: Bearer {{accessToken}}
