@server = http://localhost:8000
@json = application/json
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoNHZydXQ0IiwidXNlcklkIjoiZDgzNjU4ODgtMjEyYi00OWJhLWJiYmYtNDVhMDg0ODBjYmUzIiwidHlwZSI6IkFDQ0VTUyIsImlhdCI6MTc3MDE1NTMxNSwiZXhwIjoxNzcwMTU2MjE1fQ.0VI_6ksqqgh7-8dJGQSzuIyC5tFddlBozzpJHsxjOpk
@refreshToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIiLCJ1aWQiOjYsInR5cGUiOiJSRUZSRVNIIiwiaWF0IjoxNzY4MjMyNzI1LCJleHAiOjE3Njk0NDIzMjV9.rTokMpr0y0WbdbJ2K4TKJl89Gemmy6ECYh8b8vbUn58


POST {{server}}/orders/create
Authorization: Bearer {{accessToken}}
Content-Type: {{json}}

{
    "productId": 6,
    "quantity": 5
}
########################################
GET {{server}}/orders/health
Authorization: Bearer {{accessToken}}
########################################
GET {{server}}/products/6
Authorization: Bearer {{accessToken}}
#######################################
GET {{server}}/products/all
Authorization: Bearer {{accessToken}}
########################################
GET {{server}}/products/health
Authorization: Bearer {{accessToken}}
########################################
POST {{server}}/products/create
Authorization: Bearer {{accessToken}}
Content-Type: {{json}}

{
    "name": "The Wall",
    "artistName": "Pink Floyd",
    "year": 1979,
    "condition": "MINT",
    "price": 65000,
    "stock": 5,
    "isLimited": true,
    "saleStartAt": "2026-02-10T10:00:00"
}
########################################
GET {{server}}/users/health
Authorization: Bearer {{accessToken}}
########################################
GET {{server}}/users/me
Authorization: Bearer {{accessToken}}
########################################
POST {{server}}/auth/register
Content-Type: {{json}}

{
  "username": "h4vrut4",
  "password": "H$VRUT$",
  "name": "aa",
  "email": "abc@naver.com"
}
########################################
POST {{server}}/auth/login
Content-Type: {{json}}

{
  "username": "h4vrut4",
  "password": "H$VRUT$"
}
########################################
POST {{server}}/auth/logout
Authorization: Bearer {{accessToken}}
